CREATE TABLE `VOX_AMBASSADOR_ACADEMY_RECORD` (
  `ID`              BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME   NOT NULL,
  `UPDATE_DATETIME` DATETIME   NOT NULL,
  `AMBASSADOR_ID`   BIGINT(20) NULL     DEFAULT '0',
  `RECORD_TYPE`     INT(11)    NOT NULL DEFAULT '0',
  `DISABLED`        BIT(1)     NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `IDX_AMBASSADOR_ID` (`AMBASSADOR_ID`) USING BTREE
)
  ENGINE = InnoDB;