CREATE TABLE `VOX_AMBASSADOR_LEVEL_HISTORY` (
  `ID`              BIGINT(20)   NOT NULL  AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  `AMBASSADOR_ID`   BIGINT(20)   NULL      DEFAULT '0',
  `SCHOOL_ID`       BIGINT(20)   NULL      DEFAULT '0',
  `LEVEL`           VARCHAR(128) NOT NULL  DEFAULT '',
  `MONTH`           INT(11)      NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_AMBASSADOR_ID` (`AMBASSADOR_ID`) USING BTREE
)
  ENGINE = InnoDB;