CREATE TABLE `VOX_CLAZZ_ZONE_BAG` (
  `ID`          BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID`     BIGINT(20) NOT NULL,
  `PRODUCT_ID`  BIGINT(20) NOT NULL,
  `EXPIRE_DATE` DATETIME   NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_USERID` (`USER_ID`)
)
  ENGINE = InnoDB;