CREATE TABLE `VOX_USER_MOOD` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `TITLE`           VARCHAR(255) NOT NULL,
  `DESCRIPTION`     VARCHAR(255) NOT NULL,
  `IMG_URL`         VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;