CREATE TABLE MDB_CLAZZ_ZONE_PRODUCT (
  ID                 BIGINT NOT NULL PRIMARY KEY,
  NAME               VARCHAR(255),
  PRICE              INT,
  CURRENCY           VARCHAR(255),
  SPECIES            VARCHAR(255),
  SUBSPECIES         VARCHAR(255),
  PERIOD_OF_VALIDITY BIGINT
);

CREATE INDEX IDX_MDB_CLAZZ_ZONE_PRODUCT_SPECIES
  ON MDB_CLAZZ_ZONE_PRODUCT (SPECIES);