<#import "../../layout_default.ftl" as layout_default>
<@layout_default.page page_title='我的工作台' page_num=1>
<div class="row-fluid sortable ui-sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-star-empty"></i>超额新增</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered" id="DataTables_Table_0"
                       aria-describedby="DataTables_Table_0_info">
                    <thead>
                    <tr>
                        <th style="width:80px; text-align: center; vertical-align: middle;">区域编码</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">所属大区</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">所属市</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">所属区</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">城市等级</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">高低渗</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">城市模式</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">新增认证<br>(3-6月)</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">新增认证目标</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">完成率</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">超额奖励</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">代理名称</th>
                        <th style="width:80px; text-align: center; vertical-align: middle;">备注</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>130603</td>
                        <td>华北大区</td>
                        <td>保定市</td>
                        <td>北市区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>7178</td>
                        <td>7000</td>
                        <td>103%</td>
                        <td> 7,178.00</td>
                        <td>北京巨信科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>210213</td>
                        <td>东北大区</td>
                        <td>大连市</td>
                        <td>金州区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>9790</td>
                        <td>6000</td>
                        <td>163%</td>
                        <td> 19,580.00</td>
                        <td>大连亿智信息技术有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>420281</td>
                        <td>两湖大区</td>
                        <td>黄石市</td>
                        <td>大冶市</td>
                        <td>C</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6142</td>
                        <td>5000</td>
                        <td>123%</td>
                        <td> 6,142.00</td>
                        <td>黄石市七天网络科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>440604</td>
                        <td>华南二区</td>
                        <td>佛山市</td>
                        <td>禅城区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10686</td>
                        <td>10000</td>
                        <td>107%</td>
                        <td> 21,372.00</td>
                        <td>佛山市点高教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>350181</td>
                        <td>东南大区</td>
                        <td>福州市</td>
                        <td>福清市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5850</td>
                        <td>4000</td>
                        <td>146%</td>
                        <td> 11,700.00</td>
                        <td>鲤城区弘恩教育咨询服务中心</td>
                        <td>*2.1签约5.31解约</td>
                    </tr>
                    <tr>
                        <td>360702</td>
                        <td>东南大区</td>
                        <td>赣州市</td>
                        <td>章贡区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>11161</td>
                        <td>10000</td>
                        <td>112%</td>
                        <td> 11,161.00</td>
                        <td>赣州市弘烁智能科技发展有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330110</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>余杭区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>11216</td>
                        <td>5500</td>
                        <td>204%</td>
                        <td> 22,432.00</td>
                        <td>杭州鸿熙教育咨询有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330106</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>西湖区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>11673</td>
                        <td>7000</td>
                        <td>167%</td>
                        <td> 23,346.00</td>
                        <td>杭州鸿熙教育咨询有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330104</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>江干区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>9638</td>
                        <td>7000</td>
                        <td>138%</td>
                        <td> 19,276.00</td>
                        <td>杭州鸿熙教育咨询有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330105</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>拱墅区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6655</td>
                        <td>6000</td>
                        <td>111%</td>
                        <td> 13,310.00</td>
                        <td>杭州鸿熙教育咨询有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330102</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>上城区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>3130</td>
                        <td>2000</td>
                        <td>157%</td>
                        <td> 6,260.00</td>
                        <td>杭州市江干区浩扬教育咨询工作室</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330109</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>萧山区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>7823</td>
                        <td>5000</td>
                        <td>156%</td>
                        <td> 15,646.00</td>
                        <td>杭州市江干区浩扬教育咨询工作室</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330108</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>滨江区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6394</td>
                        <td>6000</td>
                        <td>107%</td>
                        <td> 12,788.00</td>
                        <td>杭州市江干区浩扬教育咨询工作室</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330103</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>下城区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5083</td>
                        <td>5000</td>
                        <td>102%</td>
                        <td> 10,166.00</td>
                        <td>杭州市江干区浩扬教育咨询工作室</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330183</td>
                        <td>江浙大区</td>
                        <td>杭州市</td>
                        <td>富阳市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>3533</td>
                        <td>3500</td>
                        <td>101%</td>
                        <td> 7,066.00</td>
                        <td>杭州市江干区浩扬教育咨询工作室</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>441303</td>
                        <td>华南二区</td>
                        <td>惠州市</td>
                        <td>惠阳区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6733</td>
                        <td>6000</td>
                        <td>112%</td>
                        <td> 6,733.00</td>
                        <td>惠州市广惠教育咨询有限公司</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>330784</td>
                        <td>江浙大区</td>
                        <td>金华市</td>
                        <td>永康市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5520</td>
                        <td>3000</td>
                        <td>184%</td>
                        <td> 11,040.00</td>
                        <td>金华讯吉信息技术有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330702</td>
                        <td>江浙大区</td>
                        <td>金华市</td>
                        <td>婺城区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5850</td>
                        <td>4000</td>
                        <td>146%</td>
                        <td> 11,700.00</td>
                        <td>金华讯吉信息技术有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330782</td>
                        <td>江浙大区</td>
                        <td>金华市</td>
                        <td>义乌市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6274</td>
                        <td>5000</td>
                        <td>125%</td>
                        <td> 12,548.00</td>
                        <td>金华讯吉信息技术有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>371311</td>
                        <td>鲁西大区</td>
                        <td>临沂市</td>
                        <td>罗庄区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6347</td>
                        <td>5000</td>
                        <td>127%</td>
                        <td> 6,347.00</td>
                        <td>李攀</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>371312</td>
                        <td>鲁西大区</td>
                        <td>临沂市</td>
                        <td>河东区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>4017</td>
                        <td>4000</td>
                        <td>100%</td>
                        <td> 4,017.00</td>
                        <td>李攀</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>321323</td>
                        <td>华东一区</td>
                        <td>宿迁市</td>
                        <td>泗阳县</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6547</td>
                        <td>5000</td>
                        <td>131%</td>
                        <td> 6,547.00</td>
                        <td>南京三慧文化发展有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>321324</td>
                        <td>华东一区</td>
                        <td>宿迁市</td>
                        <td>泗洪县</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5384</td>
                        <td>5000</td>
                        <td>108%</td>
                        <td> 5,384.00</td>
                        <td>南京三慧文化发展有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>320211</td>
                        <td>华东二区</td>
                        <td>无锡市</td>
                        <td>滨湖区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>8046</td>
                        <td>8000</td>
                        <td>101%</td>
                        <td> 16,092.00</td>
                        <td>南京三启教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>320682</td>
                        <td>华东一区</td>
                        <td>南通市</td>
                        <td>如皋市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>9770</td>
                        <td>6000</td>
                        <td>163%</td>
                        <td> 19,540.00</td>
                        <td>南京三启教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>320583</td>
                        <td>华东一区</td>
                        <td>苏州市</td>
                        <td>昆山市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>14241</td>
                        <td>10000</td>
                        <td>142%</td>
                        <td> 28,482.00</td>
                        <td>南京三启教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>320509</td>
                        <td>华东一区</td>
                        <td>苏州市</td>
                        <td>吴江区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10468</td>
                        <td>10000</td>
                        <td>105%</td>
                        <td> 20,936.00</td>
                        <td>南京三启教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>370202</td>
                        <td>鲁东大区</td>
                        <td>青岛市</td>
                        <td>市南区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>3345</td>
                        <td>2000</td>
                        <td>167%</td>
                        <td> 6,690.00</td>
                        <td>青岛文轩阁文化艺术交流有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>370203</td>
                        <td>鲁东大区</td>
                        <td>青岛市</td>
                        <td>市北区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>7172</td>
                        <td>6000</td>
                        <td>120%</td>
                        <td> 14,344.00</td>
                        <td>青岛文轩阁文化艺术交流有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>370212</td>
                        <td>鲁东大区</td>
                        <td>青岛市</td>
                        <td>崂山区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>3419</td>
                        <td>3000</td>
                        <td>114%</td>
                        <td> 6,838.00</td>
                        <td>青岛文轩阁文化艺术交流有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>310104</td>
                        <td>上海大区</td>
                        <td>上海市</td>
                        <td>徐汇区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>14055</td>
                        <td>10000</td>
                        <td>141%</td>
                        <td> 8,433.00</td>
                        <td>上海易才文化传播有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>310107</td>
                        <td>上海大区</td>
                        <td>上海市</td>
                        <td>普陀区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10723</td>
                        <td>9000</td>
                        <td>119%</td>
                        <td> 6,433.80</td>
                        <td>上海易才文化传播有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>310115</td>
                        <td>上海大区</td>
                        <td>上海市</td>
                        <td>浦东新区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>23131</td>
                        <td>22000</td>
                        <td>105%</td>
                        <td> 13,878.60</td>
                        <td>上海易才文化传播有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>130208</td>
                        <td>华北大区</td>
                        <td>唐山市</td>
                        <td>丰润区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>4633</td>
                        <td>4000</td>
                        <td>116%</td>
                        <td> 9,266.00</td>
                        <td>唐山华泽电子科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>130207</td>
                        <td>华北大区</td>
                        <td>唐山市</td>
                        <td>丰南区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>6401</td>
                        <td>5000</td>
                        <td>128%</td>
                        <td> 12,802.00</td>
                        <td>唐山市恺晋科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>120114</td>
                        <td>京津大区</td>
                        <td>天津市</td>
                        <td>武清区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>3012</td>
                        <td>2000</td>
                        <td>151%</td>
                        <td> 6,024.00</td>
                        <td>天津市爱优教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>370784</td>
                        <td>鲁东大区</td>
                        <td>潍坊市</td>
                        <td>安丘市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>11458</td>
                        <td>5000</td>
                        <td>229%</td>
                        <td> 22,916.00</td>
                        <td>潍城区西关学而掌上点读机经销处</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330382</td>
                        <td>江浙大区</td>
                        <td>温州市</td>
                        <td>乐清市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>12806</td>
                        <td>10500</td>
                        <td>122%</td>
                        <td> 25,612.00</td>
                        <td>温州童梦儿童文化产业有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330302</td>
                        <td>江浙大区</td>
                        <td>温州市</td>
                        <td>鹿城区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>14655</td>
                        <td>13000</td>
                        <td>113%</td>
                        <td> 29,310.00</td>
                        <td>温州童梦儿童文化产业有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330303</td>
                        <td>江浙大区</td>
                        <td>温州市</td>
                        <td>龙湾区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10607</td>
                        <td>10000</td>
                        <td>106%</td>
                        <td> 21,214.00</td>
                        <td>温州童梦儿童文化产业有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330304</td>
                        <td>江浙大区</td>
                        <td>温州市</td>
                        <td>瓯海区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10509</td>
                        <td>10000</td>
                        <td>105%</td>
                        <td> 21,018.00</td>
                        <td>温州童梦儿童文化产业有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>420112</td>
                        <td>两湖大区</td>
                        <td>武汉市</td>
                        <td>东西湖区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>7443</td>
                        <td>5000</td>
                        <td>149%</td>
                        <td> 14,886.00</td>
                        <td>武汉亚启蒙文化用品有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>420115</td>
                        <td>两湖大区</td>
                        <td>武汉市</td>
                        <td>江夏区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5818</td>
                        <td>4500</td>
                        <td>129%</td>
                        <td> 11,636.00</td>
                        <td>武汉亚启蒙文化用品有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>420111</td>
                        <td>两湖大区</td>
                        <td>武汉市</td>
                        <td>洪山区</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>7503</td>
                        <td>7000</td>
                        <td>107%</td>
                        <td> 15,006.00</td>
                        <td>武汉亚启蒙文化用品有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>530102</td>
                        <td>中国特区</td>
                        <td>昆明市</td>
                        <td>五华区</td>
                        <td>C</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>5093</td>
                        <td>5000</td>
                        <td>102%</td>
                        <td> 5,093.00</td>
                        <td>云南博通文化传播有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>430202</td>
                        <td>两湖大区</td>
                        <td>株洲市</td>
                        <td>荷塘区</td>
                        <td>B</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>4453</td>
                        <td>4000</td>
                        <td>111%</td>
                        <td> 4,453.00</td>
                        <td>长沙湘撼教育科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330282</td>
                        <td>江浙大区</td>
                        <td>宁波市</td>
                        <td>慈溪市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>8230</td>
                        <td>8000</td>
                        <td>103%</td>
                        <td> 16,460.00</td>
                        <td>宁波古特信息科技有限公司</td>
                        <td>*</td>
                    </tr>
                    <tr>
                        <td>330681</td>
                        <td>江浙大区</td>
                        <td>绍兴市</td>
                        <td>诸暨市</td>
                        <td>A</td>
                        <td>低渗</td>
                        <td>代理</td>
                        <td>10080</td>
                        <td>7000</td>
                        <td>144%</td>
                        <td> 20,160.00</td>
                        <td>诸暨市文越教育信息咨询有限公司</td>
                        <td>*</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</@layout_default.page>