CREATE TABLE `VOX_AFENTI_LEARNING_PLAN_USER_FOOTPRINT` (
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `CREATETIME`  DATETIME    NOT NULL,
  `UPDATETIME`  DATETIME    NOT NULL,
  `USER_ID`     BIGINT(20)  NOT NULL,
  `NEW_BOOK_ID` VARCHAR(64) NOT NULL,
  `NEW_UNIT_ID` VARCHAR(64) NOT NULL,
  `RANK`        INT(11)     NOT NULL,
  `SUBJECT`     VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_UID_S` (`USER_ID`, `SUBJECT`) USING BTREE
)
  ENGINE = InnoDB;