
/*
 * SHANGHAI SUNNY EDUCATION, INC. CONFIDENTIAL
 *
 * Copyright 2006-2015 Shanghai Sunny Education, Inc. All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of
 * Shanghai Sunny Education, Inc. and its suppliers, if any. The intellectual
 * and technical concepts contained herein are proprietary to Shanghai Sunny
 * Education, Inc. and its suppliers and may be covered by patents, patents
 * in process, and are protected by trade secret or copyright law. Dissemination
 * of this information or reproduction of this material is strictly forbidden
 * unless prior written permission is obtained from Shanghai Sunny Education, Inc.
 */

package com.voxlearning.ucenter.controller.connect.impl.timeepwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginWsPortType", targetNamespace = "http://webservice.xueshe17.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginWsPortType {


    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.xueshe17.com")
    @RequestWrapper(localName = "checkLoginInfo", targetNamespace = "http://webservice.xueshe17.com", className = "com.xueshe17.webservice.CheckLoginInfo")
    @ResponseWrapper(localName = "checkLoginInfoResponse", targetNamespace = "http://webservice.xueshe17.com", className = "com.xueshe17.webservice.CheckLoginInfoResponse")
    public boolean checkLoginInfo(
        @WebParam(name = "in0", targetNamespace = "http://webservice.xueshe17.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.xueshe17.com")
        String in1);

}
