CREATE TABLE `VOX_SELFSTUDY_WORDS_INCREASE` (
  `ID`                 BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `SUBJECT`            VARCHAR(16) NULL     DEFAULT NULL,
  `CLAZZ_GROUP_ID`     BIGINT(20)  NULL     DEFAULT NULL,
  `BOOK_ID`            VARCHAR(32) NULL     DEFAULT NULL,
  `UNIT_ID`            VARCHAR(32) NULL     DEFAULT NULL,
  `KNOWLEDGE_POINT_ID` VARCHAR(32) NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CLAZZ_GROUP_ID` (`CLAZZ_GROUP_ID`)
)
  ENGINE = InnoDB;