CREATE TABLE `VOX_VOICE_RECOMMEND_DATA_SENTENCE_REF` (
  `SENTENCE_ID`   BIGINT(20)   NOT NULL,
  `RECOMMEND_IDS` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`SENTENCE_ID`),
  KEY `IDX_RECOMMEND_IDS` (`RECOMMEND_IDS`)
)
  ENGINE = InnoDB;