CREATE TABLE `VOX_WEEK_PUSH_TEACHER` (
`TEACHER_ID`  BIGINT(20) NOT NULL ,
`SUBJECT_KEY`  INT(11) NOT NULL ,
`CREATE_TIME`  DATETIME  NULL  DEFAULT NULL,
PRIMARY KEY (`TEACHER_ID`)
)
  ENGINE =InnoDB;

