
-- 冗余一些字段,避免数据删除操作的影响
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN KPI_ID SMALLINT AFTER KPI_EVAL_ID;
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN KPI_NAME VARCHAR(50) AFTER KPI_ID;
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN REGION_NAME VARCHAR(50) AFTER REGION_CODE;
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN USER_NAME VARCHAR(50) AFTER USER_ID;

ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN STUDENT_AUTH_NUM_LV INT(50) NOT NULL DEFAULT 0 AFTER KPI_RESULT;

ALTER TABLE VOX_PRODUCT_CARD ADD COLUMN CARD_AMOUNT FLOAT NOT NULL DEFAULT 0 AFTER CARD_TYPE;
ALTER TABLE VOX_PRODUCT_CARD ADD COLUMN VALID_PERIOD SMALLINT NOT NULL DEFAULT 0 AFTER CARD_AMOUNT;
UPDATE VOX_PRODUCT_CARD SET CARD_AMOUNT=88, VALID_PERIOD=180 WHERE CARD_TYPE='Walker';

-- Afenti汇总表，保存Afenti成交的订单和退款的订单信息
DROP TABLE IF EXISTS AGENT_ONLINE_PAY_SHARE_DETAIL;
CREATE TABLE AGENT_ONLINE_PAY_SHARE_DETAIL (
  ID                   BIGINT(20)  NOT NULL AUTO_INCREMENT,
  KPI_EVAL_DATE       DATETIME   NOT NULL COMMENT '结算日期',
  REGION_CODE          INT         NOT NULL COMMENT '区域编码',
  REGION_NAME          VARCHAR(50) NOT NULL COMMENT '区域名称',
  PRODUCT_NAME         VARCHAR(20) NOT NULL COMMENT '产品类型',
  PAY_MONTH            VARCHAR(6)  NOT NULL COMMENT '月份',
  TOTAL_INCOME         FLOAT       NOT NULL COMMENT '总收入',
  CARD_PAY_AMOUNT      FLOAT       NOT NULL COMMENT '实物卡付费金额',
  REFUND_AMOUNT        FLOAT       NOT NULL COMMENT '退款金额',
  OPERATION_RATE       FLOAT       NOT NULL COMMENT '运营费率',
  SHAREABLE_AMOUNT     FLOAT       NOT NULL COMMENT '可分成收入',
  PAY_USER_NUM         INT         NOT NULL COMMENT '付费人数',
  MONTHLY_ACTIVE_USERS INT         NOT NULL COMMENT '月活人数',
  MONTHLY_PAY_RATE     FLOAT       NOT NULL COMMENT '月付费率',
  USER_ID               BIGINT(20)  NOT NULL COMMENT '分成用户ID',
  SHARE_AMOUNT         FLOAT       NOT NULL COMMENT '分成所得',
  CREATE_DATETIME      DATETIME    NOT NULL COMMENT '创建时间',
  UPDATE_DATETIME      DATETIME    NOT NULL COMMENT '更新时间',
  PRIMARY KEY (ID),
  INDEX IDX_USER_SHARE(USER_ID, PAY_MONTH, REGION_CODE)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =utf8;

-- UNDO
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN START_TIME DATETIME AFTER KPI_EVAL_DATE;
ALTER TABLE AGENT_USER_KPI_RESULT ADD COLUMN END_TIME DATETIME AFTER START_TIME;
ALTER TABLE AGENT_USER_KPI_RESULT MODIFY COLUMN REGION_CODE VARCHAR(500);
ALTER TABLE AGENT_USER_KPI_RESULT MODIFY COLUMN REGION_NAME VARCHAR(2000);

ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL ADD COLUMN START_TIME DATETIME AFTER KPI_EVAL_DATE;
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL ADD COLUMN END_TIME DATETIME AFTER START_TIME;
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL ADD COLUMN USER_NAME VARCHAR(50) AFTER USER_ID;
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL MODIFY COLUMN REGION_CODE VARCHAR(500);
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL MODIFY COLUMN REGION_NAME VARCHAR(2000);
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL ADD COLUMN FINANCE_CHECK BIT(1)  NOT NULL DEFAULT b'0'  comment '财务确认';
ALTER TABLE AGENT_ONLINE_PAY_SHARE_DETAIL ADD COLUMN MANAGER_CHECK BIT(1)  NOT NULL DEFAULT b'0'  comment '领导确认';
