CREATE TABLE `ADMIN_DEPARTMENT_MASTER` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` VARCHAR(50) NOT NULL,
  `USER_NAME`       VARCHAR(50) NOT NULL,
  `RIGHT_READ`      BIT(1)      NOT NULL DEFAULT b'0',
  `RIGHT_WRITE`     BIT(1)      NOT NULL DEFAULT b'0',
  `RIGHT_DELETE`    BIT(1)      NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DEPARTMENT_USER` (`USER_NAME`, `DEPARTMENT_NAME`)
)
  ENGINE = InnoDB;