CREATE TABLE `ADMIN_APP_SYSTEM` (
  `APP_NAME`        VARCHAR(50)  NOT NULL,
  `APP_DESCRIPTION` VARCHAR(255) NOT NULL,
  `CALL_BACK_URL`   VARCHAR(255) NOT NULL,
  `APP_KEY`         VARCHAR(50)  NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`APP_NAME`)
)
  ENGINE = InnoDB;