CREATE TABLE `ADMIN_ROLE` (
  `NAME`            VARCHAR(50)  NOT NULL,
  `DESCRIPTION`     VARCHAR(255) NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`NAME`)
)
  ENGINE = InnoDB;