CREATE TABLE `AGENT_GROUP_REGION` (
  `ID`              SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `GROUP_ID`        SMALLINT(6) NOT NULL,
  `REGION_CODE`     INT(11)     NOT NULL,
  `REGION_NAME`     VARCHAR(50) NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  `SCHOOL_LEVEL`    SMALLINT(6) NOT NULL DEFAULT '99',
  `DISABLED`        BIT(1)      NULL     DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `GROUP_REGION` (`GROUP_ID`, `REGION_CODE`) USING BTREE
)
  ENGINE = InnoDB;