DROP TABLE IF EXISTS AGENT_MODIFY_DICT_SCHOOL_APPLY;
CREATE TABLE `AGENT_MODIFY_DICT_SCHOOL_APPLY` (
`ID` bigint NOT NULL AUTO_INCREMENT ,
`APPLY_TYPE` varchar(30) NOT NULL COMMENT '申请类型：修改字典表申请' ,
`MODIFY_TYPE` smallint(2) NOT NULL COMMENT '字典修改类型 1：添加学校 2：删除学校' ,
`SCHOOL_ID` bigint NOT NULL ,
`SCHOOL_NAME` varchar(30) NOT NULL ,
`REGION_NAME` varchar(30) NOT NULL ,
`SCHOOL_LEVEL` smallint(6) NOT NULL ,
`USER_PLATFORM` varchar(20) NOT NULL ,
`ACCOUNT` varchar(50) NOT NULL ,
`ACCOUNT_NAME` varchar(50) NOT NULL ,
`STATUS` varchar(20) NOT NULL ,
`COMMENT` varchar(200) NULL ,
`CREATE_DATETIME` datetime NOT NULL ,
`UPDATE_DATETIME` datetime NOT NULL ,
`WORKFLOW_ID` bigint NULL COMMENT '对应的工作流ID' ,
`RESOLVED` bit NOT NULL DEFAULT b'0' COMMENT '是否已更新到字典表里面' ,
PRIMARY KEY (`ID`),
INDEX `SID_INDEX` (`SCHOOL_ID`) ,
INDEX `WID_INDEX` (`WORKFLOW_ID`)
)
DEFAULT CHARACTER SET=utf8
;


ALTER TABLE `AGENT_MODIFY_DICT_SCHOOL_APPLY`
ADD COLUMN `ENG_MODE`  smallint NULL COMMENT '英语考核模式： 1:17zuoye模式  2：快乐学模式  3：快乐学2+2模式' AFTER `SCHOOL_LEVEL`,
ADD COLUMN `MATH_MODE`  smallint NULL COMMENT '数学考核模式： 1:17zuoye模式  2：快乐学模式  3：快乐学2+2模式' AFTER `ENG_MODE`,
ADD COLUMN `SCHOOL_POPULARITY`  varchar(8) NULL AFTER `MATH_MODE`,
ADD COLUMN `MODIFY_DESC`  varchar(80) NULL AFTER `SCHOOL_POPULARITY`;


ALTER TABLE `AGENT_MODIFY_DICT_SCHOOL_APPLY`
ADD INDEX `USER_INDEX` (`USER_PLATFORM`, `ACCOUNT`),
ADD INDEX `CREATE_TIME` (`CREATE_DATETIME`) ,
ADD INDEX `STATUS_RESOLVED` (`STATUS`, `RESOLVED`) ;

ALTER TABLE `AGENT_MODIFY_DICT_SCHOOL_APPLY`
ADD COLUMN `TARGET_USER_ID`  bigint NULL COMMENT '要分配给的专员ID' AFTER `RESOLVED`;