CREATE TABLE `AGENT_GROUP_SCHOOL` (
  `ID`              INT(11)      NOT NULL AUTO_INCREMENT,
  `GROUP_ID`        SMALLINT(6)  NOT NULL,
  `REGION_CODE`     INT(11)      NOT NULL,
  `SCHOOL_ID`       BIGINT(20)   NOT NULL,
  `SCHOOL_NAME`     VARCHAR(100) NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  `DISABLED`        BIT(1)       NULL     DEFAULT b'0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GROUP_SCHOOL` (`GROUP_ID`, `SCHOOL_ID`)
)
  ENGINE = InnoDB;