CREATE TABLE `AGENT_GROUP_USER` (
  `ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL,
  `GROUP_ID` smallint(6) NOT NULL,
  `CREATE_DATETIME` datetime NOT NULL,
  `UPDATE_DATETIME` datetime NOT NULL,
  `USER_ROLE_ID` smallint(6) DEFAULT NULL,
  `DISABLED` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ID`),
  KEY `USER_GROUP` (`USER_ID`,`GROUP_ID`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

