CREATE TABLE `AGENT_USER_SCHOOL` (
  `ID`              SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `USER_ID`         BIGINT(20)  NOT NULL,
  `REGION_CODE`     INT(11)     NOT NULL,
  `SCHOOL_ID`       BIGINT(20)  NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  `DISABLED`        BIT(1)      NULL     DEFAULT b'0',
  `SCHOOL_LEVEL`    SMALLINT(6) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_SCHOOL` (`USER_ID`, `SCHOOL_ID`) USING BTREE
)
  ENGINE = InnoDB;

ALTER TABLE `AGENT_GROUP_SCHOOL` DROP INDEX `GROUP_SCHOOL`;

ALTER TABLE `AGENT_GROUP_SCHOOL`
MODIFY COLUMN `SCHOOL_NAME` varchar(100) NULL,
ADD INDEX `GROUP` (`GROUP_ID`),
ADD INDEX `SCHOOL` (`SCHOOL_ID`);