CREATE TABLE `AGENT_GROUP` (
  `ID`              SMALLINT(6)  NOT NULL AUTO_INCREMENT,
  `PARENT_ID`       SMALLINT(6)  NOT NULL,
  `GROUP_NAME`      VARCHAR(50)  NOT NULL,
  `DESCRIPTION`     VARCHAR(200) NULL     DEFAULT NULL,
  `ROLE_ID`         SMALLINT(6)  NOT NULL,
  `DISABLED`        BIT(1)       NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  `SCHOOL_LEVEL`    SMALLINT(6)  NOT NULL DEFAULT '12',
   LOGO varchar(100) DEFAULT NULL COMMENT '大区徽标',
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;