CREATE TABLE `AGENT_DICT_SCHOOL` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `SCHOOL_ID`       BIGINT(20)  NOT NULL,
  `SCHOOL_LEVEL`    SMALLINT(6) NOT NULL,
  `COUNTY_CODE`     INT(11)     NOT NULL,
  `COUNTY_NAME`     VARCHAR(50) NOT NULL,
  `BUDGET_SEP_SA`   BIGINT(20)  NOT NULL,
  `BUDGET_SEP_DA`   BIGINT(20)  NOT NULL,
  `BUDGET_OCT_SA`   BIGINT(20)  NOT NULL,
  `BUDGET_OCT_DA`   BIGINT(20)  NOT NULL,
  `BUDGET_NOV_SA`   BIGINT(20)  NOT NULL,
  `BUDGET_NOV_DA`   BIGINT(20)  NOT NULL,
  `BUDGET_DEC_SA`   BIGINT(20)  NOT NULL,
  `BUDGET_DEC_DA`   BIGINT(20)  NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  `DISABLED`        BIT(1)      NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SCHOOL_INDEX` (`SCHOOL_ID`),
  KEY `COUNTY_INDEX` (`COUNTY_CODE`)
)
  ENGINE = InnoDB;