CREATE TABLE `VOX_STUDENT_LUCKY_BAG_RECORD` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  `SENDER_ID`       BIGINT(20)  NOT NULL DEFAULT '0',
  `RECEIVER_ID`     BIGINT(20)  NOT NULL DEFAULT '0',
  `STATUS`          VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `IDX_SID` (`SENDER_ID`) USING BTREE,
  KEY `IDX_RID` (`RECEIVER_ID`) USING BTREE
)
  ENGINE = InnoDB;