CREATE TABLE `VOX_STUDENT_MAGIC_LEVEL` (
  `ID`              BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME   NOT NULL,
  `UPDATE_DATETIME` DATETIME   NOT NULL,
  `MAGICIAN_ID`     BIGINT(20) NOT NULL DEFAULT '0',
  `LEVEL`           INT(11)    NOT NULL DEFAULT '0',
  `LEVEL_VALUE`     INT(11)    NOT NULL DEFAULT '0',
  `DISABLED`        BIT(1)     NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IDX_MAGICIAN_ID` (`MAGICIAN_ID`) USING BTREE
)
  ENGINE = InnoDB;