CREATE TABLE MDB_VENDOR_APPS_RESG_REF (
  ID              BIGINT NOT NULL PRIMARY KEY,
  APP_ID          BIGINT,
  APP_KEY         VARCHAR(30),
  RESG_ID         BIGINT,
  CREATE_DATETIME TIMESTAMP,
  UPDATE_DATETIME TIMESTAMP
);

CREATE INDEX IDX_MDB_VENDOR_APPS_RESG_REF_APP_KEY
  ON MDB_VENDOR_APPS_RESG_REF (APP_KEY);