CREATE TABLE `VOX_MISSION_PROGRESS` (
  `ID`              BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME   NOT NULL,
  `UPDATE_DATETIME` DATETIME   NOT NULL,
  `MISSION_ID`      BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_MID` (`MISSION_ID`) USING BTREE
)
  ENGINE = InnoDB;