CREATE TABLE `VOX_CAMPAIGN_LOTTERY_FRAGMENT_HISTORY` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `CAMPAIGN_ID`     INT(11)      NOT NULL,
  `AWARD_ID`        INT(11)      NOT NULL DEFAULT '0',
  `AWARD_NAME`      VARCHAR(128) NOT NULL DEFAULT '',
  `USER_ID`         BIGINT(20)   NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_CID_UID` (`CAMPAIGN_ID`, `USER_ID`)
)
  ENGINE = InnoDB;