CREATE TABLE `VOX_MISSION_INTEGRAL_LOG` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  `STUDENT_ID`      BIGINT(20)  NOT NULL,
  `MISSION_ID`      BIGINT(20)  NOT NULL,
  `MONTH`           VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SID_MONTH` (`STUDENT_ID`, `MONTH`) USING BTREE,
  KEY `IDX_MONTH` (`MONTH`)
)
  ENGINE = InnoDB;