CREATE TABLE `VOX_ACTIVITY_MOTHERS_DAY_DATA` (
  `STUDENT_ID`   BIGINT(20)  NOT NULL,
  `STUDENT_NAME` VARCHAR(64) NOT NULL DEFAULT '',
  `HOMEWORK`     INT(11)     NOT NULL DEFAULT '0',
  `WORD`         INT(11)     NOT NULL DEFAULT '0',
  `KNOWLEDGE`    INT(11)     NOT NULL DEFAULT '0',
  PRIMARY KEY (`STUDENT_ID`)
)
  ENGINE = InnoDB;