CREATE TABLE `AGENT_KPI_DEF` (
  `ID`              SMALLINT(6)  NOT NULL   AUTO_INCREMENT,
  `KPI_NAME`        VARCHAR(50)  NOT NULL,
  `KPI_DESC`        VARCHAR(200) NULL       DEFAULT NULL,
  `KPI_ROLE`        SMALLINT(6)  NOT NULL,
  `KPI_CODE`        VARCHAR(30)  NOT NULL,
  `LATEST_EDITOR`   BIGINT(20)   NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;