CREATE TABLE `AGENT_ORDER` (
  `ID`                     BIGINT(20)   NOT NULL  AUTO_INCREMENT,
  `CREATOR`                VARCHAR(200) NOT NULL,
  `CREATOR_NAME`           VARCHAR(200) NULL      DEFAULT NULL,
  `CREATOR_GROUP`          SMALLINT(6)  NOT NULL,
  `ORDER_TYPE`             TINYINT(4)   NOT NULL,
  `ORDER_AMOUNT`           FLOAT        NOT NULL,
  `POINT_CHARGE_AMOUNT`    FLOAT        NULL      DEFAULT '0',
  `ORDER_NOTES`            TEXT         NULL,
  `ORDER_STATUS`           TINYINT(4)   NOT NULL,
  `LATEST_PROCESSOR`       VARCHAR(200) NOT NULL,
  `LATEST_PROCESSOR_NAME`  VARCHAR(200) NULL      DEFAULT NULL,
  `LATEST_PROCESSOR_GROUP` SMALLINT(6)  NOT NULL,
  `CREATE_DATETIME`        DATETIME     NOT NULL,
  `UPDATE_DATETIME`        DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ACCOUNT` (`CREATOR`)
)
  ENGINE = InnoDB;