CREATE TABLE `AGENT_DICT_DIM_REGION` (
  `ID`                    BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID`            BIGINT(20)   NULL     DEFAULT NULL,
  `CITY_MODEL`            VARCHAR(255) NULL     DEFAULT NULL,
  `CITY_LEVEL`            VARCHAR(255) NULL     DEFAULT NULL,
  `SPRING_MAIN_CITY`      VARCHAR(255) NULL     DEFAULT NULL,
  `CITY_SETTLEMENT`       VARCHAR(255) NULL     DEFAULT NULL,
  `MARKET_STU_LEVEL`      VARCHAR(255) NULL     DEFAULT NULL,
  `ADD_BUDGET`            BIGINT(20)   NULL     DEFAULT NULL,
  `MAR_BUDGET`            BIGINT(20)   NULL     DEFAULT NULL,
  `APR_BUDGET`            BIGINT(20)   NULL     DEFAULT NULL,
  `MAY_BUDGET`            BIGINT(20)   NULL     DEFAULT NULL,
  `JUN_BUDGET`            BIGINT(20)   NULL     DEFAULT NULL,
  `DOUBLE_SUBJECT_BUDGET` BIGINT(20)   NULL     DEFAULT NULL,
  `GRADE_MATH_ADD_BUDGET` BIGINT(20)   NULL     DEFAULT NULL,
  `STU_NUM_EXP_SIX`       BIGINT(20)   NULL     DEFAULT NULL,
  `CREATETIME`            DATETIME     NULL     DEFAULT NULL,
  `UPDATETIME`            DATETIME     NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COUNTRY_ID` (`COUNTRY_ID`, `SPRING_MAIN_CITY`(191), `MARKET_STU_LEVEL`(191))
)
  ENGINE = InnoDB;