CREATE TABLE `AGENT_VIEW_USER_REGION` (
  `ID`              INT(11)     NOT NULL AUTO_INCREMENT,
  `USER_ID`         BIGINT(20)  NOT NULL,
  `REGION_CODE`     INT(11)     NOT NULL,
  `REGION_NAME`     VARCHAR(50) NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_REGION` (`USER_ID`, `REGION_CODE`)
)
  ENGINE = InnoDB;