CREATE TABLE `AGENT_PERFORMANCE_STATISTICS` (
`ID`  bigint NOT NULL ,
`MONTH`  int NOT NULL COMMENT '月份' ,
`REGION_GROUP_ID`  bigint NULL COMMENT '大区部门ID' ,
`REGION_GROUP_NAME`  varchar(50) NULL COMMENT '大区部门名称' ,
`CITY_GROUP_ID`  bigint NULL COMMENT '城市部门ID' ,
`CITY_GROUP_NAME`  varchar(50) NULL COMMENT '// 城市部门名称' ,
`STATISTICS_TYPE`  varchar(30) NOT NULL COMMENT '统计类型' ,
`GROUP_ID`  bigint NULL COMMENT '部门ID' ,
`GROUP_ROLE_TYPE`  varchar(30) NULL COMMENT '部门角色' ,
`USER_ID`  bigint NULL COMMENT '用户ID' ,
`USER_NAME`  varchar(50) NULL COMMENT '用户姓名' ,
`USER_ROLE_TYPE`  varchar(30) NULL COMMENT '人员角色' ,
`PERFORMANCE_KPI_TYPE`  varchar(30) NOT NULL COMMENT '业绩指标' ,
`BUDGET`  bigint NOT NULL COMMENT '预算' ,
`COMPLETE`  bigint NOT NULL COMMENT '完成' ,
`COMPLETE_RATE`  double NOT NULL COMMENT '完成率' ,
`CREATE_DATETIME` datetime  NOT NULL ,
`UPDATE_DATETIME` datetime  NOT NULL ,
PRIMARY KEY (`ID`),
INDEX `TYPE_USER_MONTH` (`STATISTICS_TYPE`, `USER_ID`, `MONTH`) ,
INDEX `TYPE_GROUP_MONTH` (`STATISTICS_TYPE`, `GROUP_ID`, `MONTH`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8
;