CREATE TABLE `AGENT_APP_STICKY` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `APP_KEY`         VARCHAR(128) NOT NULL,
  `BEGIN_DAY`       INT(11)      NOT NULL,
  `CURRENT_DAY`     INT(11)      NOT NULL,
  `USER_COUNT`      INT(11)      NOT NULL,
  `STATUS`          BIT(1)       NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_APP_KEY` (`APP_KEY`) USING BTREE,
  KEY `IDX_BEGIN_DAY` (`BEGIN_DAY`) USING BTREE
)
  ENGINE = InnoDB;