CREATE TABLE `AGENT_SYS_PATH` (
  `ID`              SMALLINT(6)  NOT NULL AUTO_INCREMENT,
  `APP_NAME`        VARCHAR(50)  NOT NULL,
  `PATH_NAME`       VARCHAR(80)  NOT NULL,
  `DESCRIPTION`     VARCHAR(200) NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `APP_PATH` (`APP_NAME`, `PATH_NAME`)
)
  ENGINE = InnoDB;