CREATE TABLE `AGENT_VIEW_USER` (
  `ID`              INT(11)    NOT NULL AUTO_INCREMENT,
  `USER_ID`         BIGINT(20) NOT NULL,
  `PARENT_USER_ID`  BIGINT(20) NOT NULL,
  `CREATE_DATETIME` DATETIME   NOT NULL,
  `UPDATE_DATETIME` DATETIME   NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_PARENT` (`PARENT_USER_ID`, `USER_ID`)
)
  ENGINE = InnoDB;