CREATE TABLE `AGENT_VENDOR_APP_REF` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `APP_KEY`         VARCHAR(128) NOT NULL,
  `USER_ID`         BIGINT(20)   NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_APP_KEY` (`APP_KEY`) USING BTREE,
  KEY `IDX_USER_ID` (`USER_ID`) USING BTREE
)
  ENGINE = InnoDB;