CREATE TABLE `AGENT_PRODUCT` (
  `ID`              SMALLINT(6)  NOT NULL AUTO_INCREMENT,
  `PRODUCT_TYPE`    TINYINT(4)   NOT NULL DEFAULT '1',
  `PRODUCT_NAME`    VARCHAR(50)  NOT NULL,
  `PRODUCT_DESC`    VARCHAR(200) NULL     DEFAULT NULL,
  `PRODUCT_IMG1`    VARCHAR(100) NULL     DEFAULT NULL,
  `PRODUCT_IMG2`    VARCHAR(100) NULL     DEFAULT NULL,
  `PRODUCT_IMG3`    VARCHAR(100) NULL     DEFAULT NULL,
  `PRODUCT_IMG4`    VARCHAR(100) NULL     DEFAULT NULL,
  `PRICE`           FLOAT        NOT NULL,
  `DISCOUNT_PRICE`  FLOAT        NOT NULL,
  `VALID_FROM`      DATETIME     NULL     DEFAULT NULL,
  `VALID_TO`        DATETIME     NULL     DEFAULT NULL,
  `REGION_LIMIT`    BIT(1)       NOT NULL DEFAULT b'0',
  `LATEST_EDITOR`   BIGINT(20)   NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;