CREATE TABLE `AGENT_APP_STATISTICS_DAY` (
  `ID`              BIGINT(20)     NOT NULL AUTO_INCREMENT,
  `DAY`             INT(11)        NOT NULL,
  `APP_KEY`         VARCHAR(128)   NOT NULL,
  `USER_COUNT`      INT(11)        NOT NULL DEFAULT '0',
  `NEW_USER_COUNT`  INT(11)        NOT NULL DEFAULT '0',
  `PAID_AMOUNT`     DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `PROCEDURE_FEES`  DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `PAID_USER_COUNT` INT(11)        NOT NULL DEFAULT '0',
  `REFUND_AMOUNT`   DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `PAID_RATE`       DECIMAL(10, 4) NOT NULL DEFAULT '0.0000',
  `ARPU`            DECIMAL(10, 4) NOT NULL DEFAULT '0.0000',
  `STATUS`          BIT(1)         NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME       NOT NULL,
  `UPDATE_DATETIME` DATETIME       NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_APP_KEY` (`APP_KEY`) USING BTREE,
  KEY `IDX_DAY` (`DAY`) USING BTREE
)
  ENGINE = InnoDB;