CREATE TABLE `AGENT_DICT_AREA_SCHOOL` (
  `ID`               BIGINT(20)   NOT NULL   AUTO_INCREMENT,
  `SCHOOL_ID`        BIGINT(20)   NULL       DEFAULT NULL,
  `CREATETIME`       DATETIME     NOT NULL,
  `UPDATETIME`       DATETIME     NOT NULL,
  `DISABLED`         BIT(1)       NOT NULL,
  `MARKET_STU_LEVEL` VARCHAR(255) NULL       DEFAULT NULL,
  `COUNTY_CODE`      BIGINT(20)   NULL       DEFAULT NULL,
  `CITY_SETTLEMENT`  VARCHAR(255) NULL       DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `COUNTY_CODE` (`COUNTY_CODE`, `MARKET_STU_LEVEL`(191))
)
  ENGINE = InnoDB;