CREATE TABLE `AGENT_CITY_STUDENT` (
  `ID`                  SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME`     DATETIME    NOT NULL,
  `UPDATE_DATETIME`     DATETIME    NOT NULL,
  `DISABLED`            BIT(1)      NOT NULL,
  `REGION_CODE`         INT(11)     NOT NULL,
  `REGION_NAME`         VARCHAR(50) NOT NULL,
  `TOTAL_STUDENT_COUNT` INT(11)     NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `INDEX_REGION_CODE` (`REGION_CODE`) USING BTREE
)
  ENGINE = InnoDB;