CREATE TABLE `AGENT_TEACHER_NOTE` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `USER_ID`         BIGINT(20)   NOT NULL,
  `TEACHER_ID`      BIGINT(20)   NOT NULL,
  `NOTES`           VARCHAR(200) NULL     DEFAULT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_TEACHER` (`TEACHER_ID`)
)
  ENGINE = InnoDB;