CREATE TABLE `AGENT_KPI_ASSESSMENT` (
  `ID`              SMALLINT(6) NOT NULL   AUTO_INCREMENT,
  `KPI_ID`          SMALLINT(6) NOT NULL,
  `BASELINE`        INT(11)     NULL       DEFAULT NULL,
  `CASH_REWARD`     FLOAT       NULL       DEFAULT NULL,
  `POINT_REWARD`    FLOAT       NULL       DEFAULT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `KPI_ASSESSMENT` (`KPI_ID`)
)
  ENGINE = InnoDB;