CREATE TABLE `AGENT_ORDER_PRODUCT` (
  `ID`               BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `ORDER_ID`         BIGINT(20)  NOT NULL,
  `PRODUCT_TYPE`     TINYINT(4)  NOT NULL DEFAULT '1',
  `PRODUCT_ID`       SMALLINT(6) NOT NULL,
  `PRODUCT_QUANTITY` SMALLINT(6) NULL     DEFAULT NULL,
  `RANK`             SMALLINT(6) NOT NULL,
  `CREATE_DATETIME`  DATETIME    NOT NULL,
  `UPDATE_DATETIME`  DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_ORDER_ID` (`ORDER_ID`)
)
  ENGINE = InnoDB;