CREATE TABLE `AGENT_USER_KPI` (
  `ID`              INT(11)     NOT NULL AUTO_INCREMENT,
  `USER_ID`         SMALLINT(6) NOT NULL,
  `KPI_EVAL_ID`     SMALLINT(6) NOT NULL,
  `REGION_CODE`     INT(11)     NOT NULL DEFAULT '0',
  `KPI_TARGET`      INT(11)     NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_KPI` (`USER_ID`, `KPI_EVAL_ID`)
)
  ENGINE = InnoDB;