CREATE TABLE `AGENT_NOTIFY_USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTIFY_ID` bigint(20) NOT NULL COMMENT '通知ID',
  `USER_ID` bigint(20) NOT NULL COMMENT '通知对象ID',
  `READ_FLAG` bit(1) NOT NULL DEFAULT b'0' COMMENT '阅读状态0:未阅 1:已阅',
  `CREATE_DATETIME` datetime NOT NULL,
  `UPDATE_DATETIME` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_USER_NOTIFY` (`USER_ID`,`NOTIFY_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `AGENT_NOTIFY_USER`
ADD COLUMN `NOTIFY_TYPE`  varchar(30) NULL AFTER `USER_ID`;
