CREATE TABLE `AGENT_NOTIFY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOTIFY_TYPE` varchar(30) NOT NULL COMMENT '通知类型',
  `NOTIFY_CONTENT` varchar(200) NOT NULL COMMENT '通知内容',
  `FILE1` varchar(100) DEFAULT NULL COMMENT '通知附件1',
  `FILE2` varchar(100) DEFAULT NULL COMMENT '通知附件2',
  `CREATE_DATETIME` datetime NOT NULL,
  `UPDATE_DATETIME` datetime NOT NULL,
  `NOTIFY_TITLE` varchar(100) DEFAULT NULL COMMENT '通知title',
  `NOTIFY_URL` varchar(200) DEFAULT NULL COMMENT '通知跳转链接',
  PRIMARY KEY (`ID`),
  KEY `IDX_NOTIFY_TYPE` (`NOTIFY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

