CREATE TABLE `AGENT_APP_STATISTICS_MONTH` (
  `ID`               BIGINT(20)     NOT NULL AUTO_INCREMENT,
  `MONTH`            INT(11)        NOT NULL,
  `APP_KEY`          VARCHAR(128)   NOT NULL,
  `TOTAL_REVENUE`    DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `PROCEDURE_FEES`   DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `PAID_RATE`        DECIMAL(10, 4) NOT NULL DEFAULT '0.0000',
  `REFUND_AMOUNT`    DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `SHARED_REVENUE`   DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `DESERVED_REVENUE` DECIMAL(10, 2) NOT NULL DEFAULT '0.00',
  `STATUS`           BIT(1)         NOT NULL DEFAULT b'0',
  `CREATE_DATETIME`  DATETIME       NOT NULL,
  `UPDATE_DATETIME`  DATETIME       NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_APP_KEY` (`APP_KEY`) USING BTREE,
  KEY `IDX_MONTH` (`MONTH`) USING BTREE
)
  ENGINE = InnoDB;