CREATE TABLE VOX_USER_READING_REF(
  ID                BIGINT(20)    NOT NULL AUTO_INCREMENT,
  PICTURE_BOOK_ID   VARCHAR(50)   NOT NULL,
  USER_ID           BIGINT(20)    NOT NULL,
  SELF_STUDY_TYPE   VARCHAR(20)   NOT NULL,
  CREATE_DATETIME   DATETIME      NOT NULL,
  UPDATE_DATETIME   DATETIME      NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY IDX_USER_READING_REF (USER_ID, PICTURE_BOOK_ID)
)
ENGINE = InnoDB;