CREATE TABLE VOX_READING_ZDY
(
    ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OWNER_ID BIGINT(20) NOT NULL,
    MEMBER_ID BIGINT(20) NOT NULL,
    CREATE_DATETIME DATETIME NOT NULL,
    UPDATE_DATETIME DATETIME NOT NULL,
    SOURCE VARCHAR(32) NOT NULL DEFAULT 'unknown',
  INDEX IDX_OWNER_ID(OWNER_ID),
  UNIQUE KEY IDX_MEMBER_ID(MEMBER_ID)
);