CREATE TABLE VOX_USER_GROWTH_MISSION_REF (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT(20) NOT NULL,
  MISSION_ID VARCHAR(50) NOT NULL,
  IS_FINISHED BIT(1) NOT NULL DEFAULT b'0',
  CREATE_DATETIME DATETIME NOT NULL,
  UPDATE_DATETIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY IDX_USER_MISSION_REF (USER_ID, MISSION_ID)
)
ENGINE = InnoDB;