CREATE TABLE `VOX_JXT_NEWS_CATEGORY` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `PARENT_ID`       BIGINT(20)  NOT NULL,
  `CATEGORY_NAME`   VARCHAR(20) NOT NULL,
  `DISABLED`        BIT(1)      NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;