CREATE TABLE `VOX_VENDOR_RESG_CONTENT` (
  `ID`              BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `RESG_ID`         BIGINT(20)  NOT NULL,
  `RES_NAME`        VARCHAR(50) NOT NULL,
  `CREATE_DATETIME` DATETIME    NOT NULL,
  `UPDATE_DATETIME` DATETIME    NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_RESG_ID` (`RESG_ID`)
)
  ENGINE = InnoDB;