CREATE TABLE VOX_CHALLENGE_TEAM_INFO(
  ID              BIGINT(20)   NOT NULL  AUTO_INCREMENT,
  TEACHER_ID      BIGINT(20)   NOT NULL,
  CLAZZ_ID        BIGINT(20)   NOT NULL,
  DISABLED        BIT(1)       NOT NULL  DEFAULT b'0',
  CREATE_DATETIME DATETIME     NOT NULL,
  UPDATE_DATETIME DATETIME     NOT NULL,
  PRIMARY KEY (ID),
  KEY IDX_TEACHER_CLAZZ_ID(TEACHER_ID,CLAZZ_ID)
)
  ENGINE = InnoDB;