CREATE TABLE `VOX_OFFICIAL_ACCOUNTS` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  `NAME`            VARCHAR(256) NOT NULL DEFAULT '',
  `TITLE`           VARCHAR(256) NOT NULL DEFAULT '',
  `IMG_URL`         VARCHAR(256) NOT NULL DEFAULT '',
  `STATUS`          VARCHAR(10)  NOT NULL DEFAULT '',
  `DISABLED`        BIT(1)       NOT NULL DEFAULT b'0',
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB;