CREATE TABLE `VOX_OFFICIAL_ACCOUNTS_TARGET` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID`      BIGINT(20)   NOT NULL,
  `TARGET_TYPE`     TINYINT(4)   NOT NULL,
  `TARGET_STR`      VARCHAR(255) NOT NULL,
  `DISABLED`        BIT(1)       NOT NULL DEFAULT b'0',
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_AD_ID` (`ACCOUNT_ID`)
)
  ENGINE = InnoDB;