CREATE TABLE `VOX_USER_OFFICIAL_ACCOUNTS_REF_{}` (
  `ID`              BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID`         BIGINT(20) NOT NULL,
  `OFFICIAL_ACCOUNTS_ID`     BIGINT(20) NOT NULL,
  `ACCOUNTS_KEY`    VARCHAR(128)   NOT NULL DEFAULT '',
  `STATUS`          VARCHAR(64)    NOT NULL DEFAULT '',
  `CREATE_DATETIME` DATETIME   NOT NULL,
  `UPDATE_DATETIME` DATETIME   NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IDX_USER_ID` (`USER_ID`)
)
  ENGINE = InnoDB;