CREATE TABLE `VOX_SHORT_URL_REF` (
  `ID`              BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `SHORT_URL`       VARCHAR(10)  NOT NULL,
  `LONG_URL`        VARCHAR(500) NOT NULL,
  `DISABLED`        BIT(1)       NOT NULL,
  `CREATE_DATETIME` DATETIME     NOT NULL,
  `UPDATE_DATETIME` DATETIME     NOT NULL,
  `SIGN`            VARCHAR(32)  NULL     DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_SHORT_URL` (`SHORT_URL`),
  UNIQUE KEY `UNIQUE_LONG_URL_SIGN` (`SIGN`)
)
  ENGINE = InnoDB;